export type IntegrationCategory = 
  | 'productivity'
  | 'social'
  | 'development'
  | 'design'
  | 'communication'
  | 'marketing'
  | 'finance'
  | 'data'
  | 'media'
  | 'gaming';

export interface Integration {
  id: string;
  name: string;
  category: IntegrationCategory;
  description: string;
  icon: string;
  website: string;
  color: string;
  tier: 'free' | 'starter' | 'pro' | 'ultra';
  features: string[];
}

export const integrationCategories: { id: IntegrationCategory; name: string; icon: string }[] = [
  { id: 'productivity', name: 'Productivity', icon: 'Briefcase' },
  { id: 'social', name: 'Social Media', icon: 'Users' },
  { id: 'development', name: 'Development', icon: 'Code' },
  { id: 'design', name: 'Design', icon: 'Palette' },
  { id: 'communication', name: 'Communication', icon: 'MessageSquare' },
  { id: 'marketing', name: 'Marketing', icon: 'TrendingUp' },
  { id: 'finance', name: 'Finance', icon: 'DollarSign' },
  { id: 'data', name: 'Data & Databases', icon: 'Database' },
  { id: 'media', name: 'Media', icon: 'Image' },
  { id: 'gaming', name: 'Gaming', icon: 'Gamepad2' },
];

export const integrations: Integration[] = [
  {
    id: 'notion',
    name: 'Notion',
    category: 'productivity',
    description: 'All-in-one workspace for notes, docs, and project management',
    icon: 'https://www.notion.so/front-davicon.ico',
    website: 'https://notion.so',
    color: '#000000',
    tier: 'free',
    features: ['Notes', 'Docs', 'Wiki', 'Project Management', 'Databases'],
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'communication',
    description: 'Business messaging app for teams',
    icon: 'https://a.slack-img.com/avatars-slack-cloudfront/img/service_256.png',
    website: 'https://slack.com',
    color: '#4A154B',
    tier: 'free',
    features: ['Channels', 'Direct Messages', 'File Sharing', 'Integrations'],
  },
  {
    id: 'discord',
    name: 'Discord',
    category: 'communication',
    description: 'Voice and text chat for communities',
    icon: 'https://discord.com/assets/favicon.ico',
    website: 'https://discord.com',
    color: '#5865F2',
    tier: 'free',
    features: ['Servers', 'Voice Channels', 'Text Chat', 'Bots'],
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'development',
    description: 'Code hosting and collaboration platform',
    icon: 'https://github.githubassets.com/favicon.ico',
    website: 'https://github.com',
    color: '#181717',
    tier: 'free',
    features: ['Git Hosting', 'Pull Requests', 'Actions', 'Issues'],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    category: 'development',
    description: 'DevOps platform with CI/CD',
    icon: 'https://about.gitlab.com/favicon.ico',
    website: 'https://gitlab.com',
    color: '#FC6D26',
    tier: 'free',
    features: ['Git Hosting', 'CI/CD', 'Code Review', 'DevOps'],
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'development',
    description: 'Frontend cloud platform for developers',
    icon: 'https://vercel.com/favicon.ico',
    website: 'https://vercel.com',
    color: '#000000',
    tier: 'free',
    features: ['Deployments', 'Serverless', 'Edge Functions', 'Analytics'],
  },
  {
    id: 'netlify',
    name: 'Netlify',
    category: 'development',
    description: 'Modern web development platform',
    icon: 'https://www.netlify.com/favicon.ico',
    website: 'https://netlify.com',
    color: '#00DC7D',
    tier: 'free',
    features: ['Deployments', 'Forms', 'Functions', 'Edge'],
  },
  {
    id: 'gcp',
    name: 'Google Cloud',
    category: 'development',
    description: 'Cloud computing services by Google',
    icon: 'https://www.google.com/favicon.ico',
    website: 'https://cloud.google.com',
    color: '#4285F4',
    tier: 'free',
    features: ['Compute', 'Storage', 'ML', 'Big Data'],
  },
  {
    id: 'aws',
    name: 'AWS',
    category: 'development',
    description: 'Cloud computing platform by Amazon',
    icon: 'https://aws.amazon.com/favicon.ico',
    website: 'https://aws.amazon.com',
    color: '#FF9900',
    tier: 'starter',
    features: ['EC2', 'S3', 'Lambda', 'RDS'],
  },
  {
    id: 'azure',
    name: 'Azure',
    category: 'development',
    description: 'Cloud computing by Microsoft',
    icon: 'https://azure.microsoft.com/favicon.ico',
    website: 'https://azure.microsoft.com',
    color: '#0078D4',
    tier: 'starter',
    features: ['Virtual Machines', 'Storage', 'AI', 'DevOps'],
  },
  {
    id: 'figma',
    name: 'Figma',
    category: 'design',
    description: 'Collaborative design tool',
    icon: 'https://www.figma.com/favicon.ico',
    website: 'https://figma.com',
    color: '#F24E1E',
    tier: 'free',
    features: ['UI Design', 'Prototyping', 'Design Systems', 'Collaboration'],
  },
  {
    id: 'canva',
    name: 'Canva',
    category: 'design',
    description: 'Graphic design platform',
    icon: 'https://www.canva.com/favicon.ico',
    website: 'https://canva.com',
    color: '#00C4CC',
    tier: 'free',
    features: ['Social Graphics', 'Presentations', 'Videos', 'Print'],
  },
  {
    id: 'adobe',
    name: 'Adobe Creative Cloud',
    category: 'design',
    description: 'Creative suite for designers',
    icon: 'https://www.adobe.com/favicon.ico',
    website: 'https://adobe.com',
    color: '#FF0000',
    tier: 'pro',
    features: ['Photoshop', 'Illustrator', 'Premiere', 'After Effects'],
  },
  {
    id: 'framer',
    name: 'Framer',
    category: 'design',
    description: 'Interactive design tool',
    icon: 'https://www.framer.com/favicon.ico',
    website: 'https://framer.com',
    color: '#000000',
    tier: 'free',
    features: ['Prototyping', 'Animation', 'Design', 'Publishing'],
  },
  {
    id: 'invision',
    name: 'InVision',
    category: 'design',
    description: 'Design collaboration and prototyping',
    icon: 'https://www.invisionapp.com/favicon.ico',
    website: 'https://invisionapp.com',
    color: '#FF3366',
    tier: 'free',
    features: ['Prototyping', 'Design Systems', 'Reviews', 'Handoff'],
  },
  {
    id: 'gmail',
    name: 'Gmail',
    category: 'communication',
    description: 'Email service by Google',
    icon: 'https://www.google.com/favicon.ico',
    website: 'https://mail.google.com',
    color: '#EA4335',
    tier: 'free',
    features: ['Email', 'Spam Filter', 'Labels', 'Calendar'],
  },
  {
    id: 'outlook',
    name: 'Outlook',
    category: 'communication',
    description: 'Email and calendar by Microsoft',
    icon: 'https://outlook.live.com/favicon.ico',
    website: 'https://outlook.com',
    color: '#0078D4',
    tier: 'free',
    features: ['Email', 'Calendar', 'Contacts', 'Tasks'],
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    category: 'communication',
    description: 'Video conferencing and chat',
    icon: 'https://teams.microsoft.com/favicon.ico',
    website: 'https://teams.microsoft.com',
    color: '#6264A7',
    tier: 'free',
    features: ['Video Calls', 'Chat', 'File Sharing', 'Integrations'],
  },
  {
    id: 'zoom',
    name: 'Zoom',
    category: 'communication',
    description: 'Video conferencing platform',
    icon: 'https://zoom.us/favicon.ico',
    website: 'https://zoom.us',
    color: '#2D8CFF',
    tier: 'free',
    features: ['Video Calls', 'Screen Share', 'Recording', 'Breakout Rooms'],
  },
  {
    id: 'google Sheets',
    name: 'Google Sheets',
    category: 'productivity',
    description: 'Spreadsheet application',
    icon: 'https://www.google.com/favicon.ico',
    website: 'https://sheets.google.com',
    color: '#34A853',
    tier: 'free',
    features: ['Spreadsheets', 'Formulas', 'Charts', 'Collaboration'],
  },
  {
    id: 'google Docs',
    name: 'Google Docs',
    category: 'productivity',
    description: 'Document editor',
    icon: 'https://www.google.com/favicon.ico',
    website: 'https://docs.google.com',
    color: '#4285F4',
    tier: 'free',
    features: ['Documents', 'Templates', 'Collaboration', 'Add-ons'],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    category: 'data',
    description: 'Low-code platform for building apps',
    icon: 'https://www.airtable.com/favicon.ico',
    website: 'https://airtable.com',
    color: '#FFB400',
    tier: 'free',
    features: ['Databases', 'Automation', 'Forms', 'Integrations'],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'data',
    description: 'Open source Firebase alternative',
    icon: 'https://supabase.com/favicon.ico',
    website: 'https://supabase.com',
    color: '#3ECF8E',
    tier: 'free',
    features: ['PostgreSQL', 'Auth', 'Storage', 'Edge Functions'],
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    category: 'data',
    description: 'Document database',
    icon: 'https://www.mongodb.com/favicon.ico',
    website: 'https://mongodb.com',
    color: '#47A248',
    tier: 'free',
    features: ['NoSQL', 'Atlas', 'Search', 'Charts'],
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'data',
    description: 'Open source relational database',
    icon: 'https://www.postgresql.org/favicon.ico',
    website: 'https://postgresql.org',
    color: '#336791',
    tier: 'free',
    features: ['SQL', 'JSON', 'Full Text Search', 'Replication'],
  },
  {
    id: 'redis',
    name: 'Redis',
    category: 'data',
    description: 'In-memory data store',
    icon: 'https://redis.io/favicon.ico',
    website: 'https://redis.io',
    color: '#DC382D',
    tier: 'free',
    features: ['Cache', 'Session', 'Pub/Sub', 'Stream'],
  },
  {
    id: 'mysql',
    name: 'MySQL',
    category: 'data',
    description: 'Open source relational database',
    icon: 'https://www.mysql.com/favicon.ico',
    website: 'https://mysql.com',
    color: '#4479A1',
    tier: 'free',
    features: ['SQL', 'Replication', 'Storage Engines', 'Cluster'],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'finance',
    description: 'Payment processing platform',
    icon: 'https://stripe.com/favicon.ico',
    website: 'https://stripe.com',
    color: '#635BFF',
    tier: 'free',
    features: ['Payments', 'Subscriptions', 'Invoicing', 'Connect'],
  },
  {
    id: 'paypal',
    name: 'PayPal',
    category: 'finance',
    description: 'Online payment service',
    icon: 'https://www.paypal.com/favicon.ico',
    website: 'https://paypal.com',
    color: '#003087',
    tier: 'free',
    features: ['Payments', 'Payouts', 'Invoicing', 'Checkout'],
  },
  {
    id: 'quickbooks',
    name: 'QuickBooks',
    category: 'finance',
    description: 'Accounting software',
    icon: 'https://quickbooks.intuit.com/favicon.ico',
    website: 'https://quickbooks.intuit.com',
    color: '#2CA01C',
    tier: 'pro',
    features: ['Invoicing', 'Expense Tracking', 'Payroll', 'Reports'],
  },
  {
    id: 'xero',
    name: 'Xero',
    category: 'finance',
    description: 'Cloud accounting software',
    icon: 'https://www.xero.com/favicon.ico',
    website: 'https://xero.com',
    color: '#13B5EA',
    tier: 'starter',
    features: ['Invoicing', 'Bank Sync', 'Payroll', 'Reporting'],
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    category: 'marketing',
    description: 'CRM and marketing platform',
    icon: 'https://www.hubspot.com/favicon.ico',
    website: 'https://hubspot.com',
    color: '#FF7A59',
    tier: 'free',
    features: ['CRM', 'Email', 'Marketing Automation', 'Analytics'],
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    category: 'marketing',
    description: 'Email marketing platform',
    icon: 'https://mailchimp.com/favicon.ico',
    website: 'https://mailchimp.com',
    color: '#FFE01A',
    tier: 'free',
    features: ['Email Campaigns', 'Automation', 'Landing Pages', 'Analytics'],
  },
  {
    id: 'buffer',
    name: 'Buffer',
    category: 'marketing',
    description: 'Social media management',
    icon: 'https://buffer.com/favicon.ico',
    website: 'https://buffer.com',
    color: '#168EEA',
    tier: 'free',
    features: ['Scheduling', 'Analytics', 'Engagement', 'Team'],
  },
  {
    id: 'hootsuite',
    name: 'Hootsuite',
    category: 'marketing',
    description: 'Social media management platform',
    icon: 'https://www.hootsuite.com/favicon.ico',
    website: 'https://hootsuite.com',
    color: '#143A05',
    tier: 'free',
    features: ['Scheduling', 'Analytics', 'Moderation', 'Content'],
  },
  {
    id: 'sproutsocial',
    name: 'Sprout Social',
    category: 'marketing',
    description: 'Social media management and analytics',
    icon: 'https://sproutsocial.com/favicon.ico',
    website: 'https://sproutsocial.com',
    color: '#00B297',
    tier: 'pro',
    features: ['Publishing', 'Analytics', 'Engagement', 'Reporting'],
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    category: 'marketing',
    description: 'CRM platform',
    icon: 'https://salesforce.com/favicon.ico',
    website: 'https://salesforce.com',
    color: '#00A1E0',
    tier: 'pro',
    features: ['CRM', 'Sales Cloud', 'Service Cloud', 'Marketing Cloud'],
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    category: 'social',
    description: 'Social media and microblogging',
    icon: 'https://twitter.com/favicon.ico',
    website: 'https://twitter.com',
    color: '#000000',
    tier: 'free',
    features: ['Tweets', 'Media', 'Spaces', 'Lists'],
  },
  {
    id: 'instagram',
    name: 'Instagram',
    category: 'social',
    description: 'Photo and video sharing',
    icon: 'https://www.instagram.com/favicon.ico',
    website: 'https://instagram.com',
    color: '#E4405F',
    tier: 'free',
    features: ['Posts', 'Stories', 'Reels', 'IGTV'],
  },
  {
    id: 'facebook',
    name: 'Facebook',
    category: 'social',
    description: 'Social media platform',
    icon: 'https://www.facebook.com/favicon.ico',
    website: 'https://facebook.com',
    color: '#1877F2',
    tier: 'free',
    features: ['Posts', 'Groups', 'Pages', 'Events'],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    category: 'social',
    description: 'Professional network',
    icon: 'https://www.linkedin.com/favicon.ico',
    website: 'https://linkedin.com',
    color: '#0A66C2',
    tier: 'free',
    features: ['Profiles', 'Jobs', 'Groups', 'Content'],
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    category: 'social',
    description: 'Short video platform',
    icon: 'https://www.tiktok.com/favicon.ico',
    website: 'https://tiktok.com',
    color: '#000000',
    tier: 'free',
    features: ['Videos', 'Live', 'Duets', 'Sound'],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    category: 'media',
    description: 'Video sharing platform',
    icon: 'https://www.youtube.com/favicon.ico',
    website: 'https://youtube.com',
    color: '#FF0000',
    tier: 'free',
    features: ['Videos', 'Live Streaming', 'Shorts', 'Monetization'],
  },
  {
    id: 'vimeo',
    name: 'Vimeo',
    category: 'media',
    description: 'Video hosting and streaming',
    icon: 'https://vimeo.com/favicon.ico',
    website: 'https://vimeo.com',
    color: '#1AB7EA',
    tier: 'free',
    features: ['Video Hosting', 'Streaming', 'Player', 'Analytics'],
  },
  {
    id: 'twitch',
    name: 'Twitch',
    category: 'gaming',
    description: 'Live streaming platform for gamers',
    icon: 'https://www.twitch.tv/favicon.ico',
    website: 'https://twitch.tv',
    color: '#9146FF',
    tier: 'free',
    features: ['Live Streaming', 'Chat', 'Clips', 'Extensions'],
  },
  {
    id: 'steam',
    name: 'Steam',
    category: 'gaming',
    description: 'Digital distribution platform',
    icon: 'https://store.steampowered.com/favicon.ico',
    website: 'https://store.steampowered.com',
    color: '#171A21',
    tier: 'free',
    features: ['Games', 'Community', 'Workshop', 'Cloud'],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'development',
    description: 'AI research and deployment',
    icon: 'https://openai.com/favicon.ico',
    website: 'https://openai.com',
    color: '#10A37F',
    tier: 'free',
    features: ['GPT', 'DALL-E', 'API', 'Fine-tuning'],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    category: 'development',
    description: 'AI safety company',
    icon: 'https://www.anthropic.com/favicon.ico',
    website: 'https://anthropic.com',
    color: '#D3B41A',
    tier: 'free',
    features: ['Claude', 'API', 'Constitutional AI', 'Haiku'],
  },
  {
    id: 'replicate',
    name: 'Replicate',
    category: 'development',
    description: 'Run ML models in the cloud',
    icon: 'https://replicate.com/favicon.ico',
    website: 'https://replicate.com',
    color: '#000000',
    tier: 'free',
    features: ['ML Models', 'API', 'Fine-tuning', 'Deployment'],
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    category: 'development',
    description: 'ML model hub',
    icon: 'https://huggingface.co/favicon.ico',
    website: 'https://huggingface.co',
    color: '#FFD21E',
    tier: 'free',
    features: ['Models', 'Datasets', 'Spaces', 'Inference'],
  },
  {
    id: 'langchain',
    name: 'LangChain',
    category: 'development',
    description: 'Build apps with LLMs',
    icon: 'https://www.langchain.com/favicon.ico',
    website: 'https://langchain.com',
    color: '#000000',
    tier: 'free',
    features: ['Chains', 'Agents', 'Memory', 'Tools'],
  },
  {
    id: 'pinecone',
    name: 'Pinecone',
    category: 'data',
    description: 'Vector database for embeddings',
    icon: 'https://www.pinecone.io/favicon.ico',
    website: 'https://pinecone.io',
    color: '#000000',
    tier: 'free',
    features: ['Vectors', 'Similarity Search', 'Metadata', 'Serverless'],
  },
  {
    id: 'weaviate',
    name: 'Weaviate',
    category: 'data',
    description: 'Open source vector database',
    icon: 'https://weaviate.io/favicon.ico',
    website: 'https://weaviate.io',
    color: '#45B32A',
    tier: 'free',
    features: ['Vectors', 'GraphQL', 'Modules', 'Hybrid Search'],
  },
  {
    id: 'qdrant',
    name: 'Qdrant',
    category: 'data',
    description: 'Vector search engine',
    icon: 'https://qdrant.tech/favicon.ico',
    website: 'https://qdrant.tech',
    color: '#000000',
    tier: 'free',
    features: ['Vectors', 'Filtering', 'Faceted Search', 'API'],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'productivity',
    description: 'Workflow automation',
    icon: 'https://zapier.com/favicon.ico',
    website: 'https://zapier.com',
    color: '#FF4F00',
    tier: 'free',
    features: ['Zaps', 'Triggers', 'Actions', 'Filters'],
  },
  {
    id: 'make',
    name: 'Make (Integromat)',
    category: 'productivity',
    description: 'Visual automation platform',
    icon: 'https://www.make.com/favicon.ico',
    website: 'https://make.com',
    color: '#2D57C9',
    tier: 'free',
    features: ['Scenarios', 'Connections', 'Routing', 'Analytics'],
  },
  {
    id: 'pipedream',
    name: 'PipeDream',
    category: 'productivity',
    description: 'Developer automation platform',
    icon: 'https://pipedream.com/favicon.ico',
    website: 'https://pipedream.com',
    color: '#000000',
    tier: 'free',
    features: ['Workflows', 'Sources', 'Actions', 'Code'],
  },
  {
    id: 'n8n',
    name: 'n8n',
    category: 'productivity',
    description: 'Free workflow automation',
    icon: 'https://n8n.io/favicon.ico',
    website: 'https://n8n.io',
    color: '#000000',
    tier: 'free',
    features: ['Workflows', 'Nodes', 'Self-hosted', 'Cloud'],
  },
  {
    id: ' IFTTT',
    name: 'IFTTT',
    category: 'productivity',
    description: 'Automation service',
    icon: 'https://ifttt.com/favicon.ico',
    website: 'https://ifttt.com',
    color: '#000000',
    tier: 'free',
    features: ['Applets', 'Triggers', 'Actions', 'Webhooks'],
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    category: 'development',
    description: 'Git code management',
    icon: 'https://bitbucket.org/favicon.ico',
    website: 'https://bitbucket.org',
    color: '#0052CC',
    tier: 'free',
    features: ['Git Hosting', 'Pipelines', 'Code Review', 'Jira'],
  },
  {
    id: 'circleci',
    name: 'CircleCI',
    category: 'development',
    description: 'CI/CD platform',
    icon: 'https://circleci.com/favicon.ico',
    website: 'https://circleci.com',
    color: '#343434',
    tier: 'free',
    features: ['CI/CD', 'Pipelines', 'Orbs', 'Testing'],
  },
  {
    id: 'travis ci',
    name: 'Travis CI',
    category: 'development',
    description: 'Distributed CI platform',
    icon: 'https://travis-ci.com/favicon.ico',
    website: 'https://travis-ci.com',
    color: '#00A04A',
    tier: 'free',
    features: ['CI/CD', 'Testing', 'Deployments', 'Add-ons'],
  },
  {
    id: 'github actions',
    name: 'GitHub Actions',
    category: 'development',
    description: 'Workflow automation',
    icon: 'https://github.githubassets.com/favicon.ico',
    website: 'https://github.com/features/actions',
    color: '#181717',
    tier: 'free',
    features: ['Workflows', 'Actions', 'Matrix', 'Artifacts'],
  },
  {
    id: 'gitlab ci',
    name: 'GitLab CI',
    category: 'development',
    description: 'CI/CD by GitLab',
    icon: 'https://about.gitlab.com/favicon.ico',
    website: 'https://docs.gitlab.com/ee/ci',
    color: '#FC6D26',
    tier: 'free',
    features: ['Pipelines', 'Jobs', 'Artifacts', 'Registry'],
  },
  {
    id: 'jenkins',
    name: 'Jenkins',
    category: 'development',
    description: 'Open source automation server',
    icon: 'https://www.jenkins.io/favicon.ico',
    website: 'https://jenkins.io',
    color: '#D24939',
    tier: 'free',
    features: ['CI/CD', 'Plugins', 'Pipelines', 'Distributed'],
  },
  {
    id: 'docker',
    name: 'Docker',
    category: 'development',
    description: 'Container platform',
    icon: 'https://www.docker.com/favicon.ico',
    website: 'https://docker.com',
    color: '#2496ED',
    tier: 'free',
    features: ['Containers', 'Hub', 'Compose', 'Swarm'],
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    category: 'development',
    description: 'Container orchestration',
    icon: 'https://kubernetes.io/favicon.ico',
    website: 'https://kubernetes.io',
    color: '#326CE5',
    tier: 'free',
    features: ['Orchestration', 'Scaling', 'Self-healing', 'Load Balancing'],
  },
  {
    id: 'terraform',
    name: 'Terraform',
    category: 'development',
    description: 'Infrastructure as code',
    icon: 'https://www.terraform.io/favicon.ico',
    website: 'https://terraform.io',
    color: '#7B42BC',
    tier: 'free',
    features: ['IaC', 'Providers', 'State', 'Modules'],
  },
  {
    id: 'ansible',
    name: 'Ansible',
    category: 'development',
    description: 'Automation tool',
    icon: 'https://www.ansible.com/favicon.ico',
    website: 'https://ansible.com',
    color: '#EE0000',
    tier: 'free',
    features: ['Automation', 'Playbooks', 'Modules', 'Tower'],
  },
  {
    id: 'firebase',
    name: 'Firebase',
    category: 'development',
    description: 'Google app development platform',
    icon: 'https://firebase.google.com/favicon.ico',
    website: 'https://firebase.google.com',
    color: '#FFCA28',
    tier: 'free',
    features: ['Auth', 'Firestore', 'Storage', 'Functions'],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'data',
    description: 'Open source Firebase alternative',
    icon: 'https://supabase.com/favicon.ico',
    website: 'https://supabase.com',
    color: '#3ECF8E',
    tier: 'free',
    features: ['PostgreSQL', 'Auth', 'Storage', 'Edge Functions'],
  },
  {
    id: 'planetscale',
    name: 'PlanetScale',
    category: 'data',
    description: 'Serverless MySQL platform',
    icon: 'https://planetscale.com/favicon.ico',
    website: 'https://planetscale.com',
    color: '#000000',
    tier: 'free',
    features: ['MySQL', 'Branching', 'Schema', 'Scaling'],
  },
  {
    id: 'neon',
    name: 'Neon',
    category: 'data',
    description: 'Serverless PostgreSQL',
    icon: 'https://neon.tech/favicon.ico',
    website: 'https://neon.tech',
    color: '#000000',
    tier: 'free',
    features: ['PostgreSQL', 'Branching', 'Auto-scaling', 'Serverless'],
  },
  {
    id: 'upstash',
    name: 'Upstash',
    category: 'data',
    description: 'Serverless Redis',
    icon: 'https://upstash.com/favicon.ico',
    website: 'https://upstash.com',
    color: '#000000',
    tier: 'free',
    features: ['Redis', 'Kafka', 'QStash', 'Rate Limiting'],
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    category: 'development',
    description: 'Web infrastructure platform',
    icon: 'https://cloudflare.com/favicon.ico',
    website: 'https://cloudflare.com',
    color: '#F38020',
    tier: 'free',
    features: ['CDN', 'DNS', 'Workers', 'Analytics'],
  },
  {
    id: 'datadog',
    name: 'Datadog',
    category: 'development',
    description: 'Cloud monitoring platform',
    icon: 'https://www.datadoghq.com/favicon.ico',
    website: 'https://datadoghq.com',
    color: '#632CA6',
    tier: 'free',
    features: ['APM', 'Logs', 'Metrics', 'Infrastructure'],
  },
  {
    id: 'sentry',
    name: 'Sentry',
    category: 'development',
    description: 'Application monitoring',
    icon: 'https://sentry.io/favicon.ico',
    website: 'https://sentry.io',
    color: '#362D59',
    tier: 'free',
    features: ['Error Tracking', 'Performance', 'Releases', 'Profiling'],
  },
  {
    id: 'newrelic',
    name: 'New Relic',
    category: 'development',
    description: 'Observability platform',
    icon: 'https://newrelic.com/favicon.ico',
    website: 'https://newrelic.com',
    color: '#000D58',
    tier: 'free',
    features: ['APM', 'Infrastructure', 'Logs', 'Browser'],
  },
  {
    id: 'linear',
    name: 'Linear',
    category: 'productivity',
    description: 'Issue tracking for software teams',
    icon: 'https://linear.app/favicon.ico',
    website: 'https://linear.app',
    color: '#000000',
    tier: 'free',
    features: ['Issues', 'Projects', 'Cycles', 'Automations'],
  },
  {
    id: 'asana',
    name: 'Asana',
    category: 'productivity',
    description: 'Work management platform',
    icon: 'https://asana.com/favicon.ico',
    website: 'https://asana.com',
    color: '#F06A6A',
    tier: 'free',
    features: ['Tasks', 'Projects', 'Timeline', 'Goals'],
  },
  {
    id: 'trello',
    name: 'Trello',
    category: 'productivity',
    description: 'Visual project management',
    icon: 'https://trello.com/favicon.ico',
    website: 'https://trello.com',
    color: '#0079BF',
    tier: 'free',
    features: ['Boards', 'Lists', 'Cards', 'Power-Ups'],
  },
  {
    id: 'monday',
    name: 'Monday.com',
    category: 'productivity',
    description: 'Work OS',
    icon: 'https://monday.com/favicon.ico',
    website: 'https://monday.com',
    color: '#FF3D57',
    tier: 'free',
    features: ['Boards', 'Dashboards', 'Automations', 'Integrations'],
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    category: 'productivity',
    description: 'All-in-one productivity platform',
    icon: 'https://clickup.com/favicon.ico',
    website: 'https://clickup.com',
    color: '#7B68EE',
    tier: 'free',
    features: ['Tasks', 'Docs', 'Goals', 'Chat'],
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'productivity',
    description: 'All-in-one workspace',
    icon: 'https://notion.so/favicon.ico',
    website: 'https://notion.so',
    color: '#000000',
    tier: 'free',
    features: ['Notes', 'Wikis', 'Projects', 'Databases'],
  },
  {
    id: 'roam',
    name: 'Roam Research',
    category: 'productivity',
    description: 'Note-taking for networked thought',
    icon: 'https://roamresearch.com/favicon.ico',
    website: 'https://roamresearch.com',
    color: '#000000',
    tier: 'free',
    features: ['Blocks', 'Links', 'Queries', 'Daily Notes'],
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'productivity',
    description: 'Second brain for notes',
    icon: 'https://obsidian.md/favicon.ico',
    website: 'https://obsidian.md',
    color: '#000000',
    tier: 'free',
    features: ['Linked Notes', 'Graph View', 'Plugins', 'Markdown'],
  },
  {
    id: 'craft',
    name: 'Craft',
    category: 'productivity',
    description: 'Beautiful document creation',
    icon: 'https://craft.do/favicon.ico',
    website: 'https://craft.do',
    color: '#000000',
    tier: 'free',
    features: ['Documents', 'Hierarchy', 'Links', 'Collaboration'],
  },
  {
    id: 'typeform',
    name: 'Typeform',
    category: 'productivity',
    description: 'Conversational forms',
    icon: 'https://typeform.com/favicon.ico',
    website: 'https://typeform.com',
    color: '#262627',
    tier: 'free',
    features: ['Forms', 'Surveys', 'Quizzes', 'Conversational'],
  },
  {
    id: 'calcom',
    name: 'Cal.com',
    category: 'productivity',
    description: 'Open source scheduling',
    icon: 'https://cal.com/favicon.ico',
    website: 'https://cal.com',
    color: '#000000',
    tier: 'free',
    features: ['Scheduling', 'Bookings', 'Team', 'Self-hosted'],
  },
  {
    id: 'calendly',
    name: 'Calendly',
    category: 'productivity',
    description: 'Meeting scheduling platform',
    icon: 'https://calendly.com/favicon.ico',
    website: 'https://calendly.com',
    color: '#006BFF',
    tier: 'free',
    features: ['Scheduling', 'Invites', 'Buffer Time', 'Integrations'],
  },
  {
    id: 'loom',
    name: 'Loom',
    category: 'communication',
    description: 'Async video messaging',
    icon: 'https://loom.com/favicon.ico',
    website: 'https://loom.com',
    color: '#625DF5',
    tier: 'free',
    features: ['Video Messages', 'Recording', 'Sharing', 'Analytics'],
  },
  {
    id: 'otter',
    name: 'Otter.ai',
    category: 'communication',
    description: 'Meeting transcription',
    icon: 'https://otter.ai/favicon.ico',
    website: 'https://otter.ai',
    color: '#000000',
    tier: 'free',
    features: ['Transcription', 'Live Notes', 'Summary', 'Collaboration'],
  },
  {
    id: 'descript',
    name: 'Descript',
    category: 'media',
    description: 'Audio/video editor',
    icon: 'https://www.descript.com/favicon.ico',
    website: 'https://descript.com',
    color: '#000000',
    tier: 'free',
    features: ['Editing', 'Transcription', 'Screen Recording', 'Publishing'],
  },
  {
    id: 'imagekit',
    name: 'ImageKit',
    category: 'media',
    description: 'Image optimization and CDN',
    icon: 'https://imagekit.io/favicon.ico',
    website: 'https://imagekit.io',
    color: '#000000',
    tier: 'free',
    features: ['Resize', 'CDN', 'Transformations', 'Storage'],
  },
  {
    id: 'cloudinary',
    name: 'Cloudinary',
    category: 'media',
    description: 'Media management platform',
    icon: 'https://cloudinary.com/favicon.ico',
    website: 'https://cloudinary.com',
    color: '#3448C5',
    tier: 'free',
    features: ['Transformations', 'CDN', 'AI', 'Video'],
  },
  {
    id: 'imgix',
    name: 'Imgix',
    category: 'media',
    description: 'Real-time image processing',
    icon: 'https://www.imgix.com/favicon.ico',
    website: 'https://www.imgix.com',
    color: '#000000',
    tier: 'free',
    features: ['Real-time', 'CDN', 'Streaming', 'Analytics'],
  },
  {
    id: 's3',
    name: 'Amazon S3',
    category: 'data',
    description: 'Object storage',
    icon: 'https://aws.amazon.com/favicon.ico',
    website: 'https://aws.amazon.com/s3',
    color: '#FF9900',
    tier: 'starter',
    features: ['Object Storage', 'Versioning', 'Lifecycle', 'Analytics'],
  },
  {
    id: 'gcs',
    name: 'Google Cloud Storage',
    category: 'data',
    description: 'Object storage by Google',
    icon: 'https://cloud.google.com/favicon.ico',
    website: 'https://cloud.google.com/storage',
    color: '#4285F4',
    tier: 'free',
    features: ['Object Storage', 'Classes', 'Lifecycle', 'Versioning'],
  },
  {
    id: 'digitalocean spaces',
    name: 'DigitalOcean Spaces',
    category: 'data',
    description: 'Object storage',
    icon: 'https://www.digitalocean.com/favicon.ico',
    website: 'https://www.digitalocean.com/products/spaces',
    color: '#0069FF',
    tier: 'free',
    features: ['S3-compatible', 'CDN', 'Analytics', 'Lifecycle'],
  },
  {
    id: 'r2',
    name: 'Cloudflare R2',
    category: 'data',
    description: 'Zero egress storage',
    icon: 'https://cloudflare.com/favicon.ico',
    website: 'https://developers.cloudflare.com/r2',
    color: '#F38020',
    tier: 'free',
    features: ['Zero Egress', 'S3-compatible', 'Integrations', 'Workers'],
  },
  {
    id: 'bun',
    name: 'Bun',
    category: 'development',
    description: 'All-in-one JavaScript runtime',
    icon: 'https://bun.sh/favicon.ico',
    website: 'https://bun.sh',
    color: '#000000',
    tier: 'free',
    features: ['Runtime', 'Package Manager', 'Bundler', 'Test Runner'],
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    category: 'development',
    description: 'JavaScript runtime',
    icon: 'https://nodejs.org/favicon.ico',
    website: 'https://nodejs.org',
    color: '#339933',
    tier: 'free',
    features: ['Runtime', 'NPM', 'Event Loop', 'Express'],
  },
  {
    id: 'deno',
    name: 'Deno',
    category: 'development',
    description: 'Secure JavaScript runtime',
    icon: 'https://deno.land/favicon.ico',
    website: 'https://deno.land',
    color: '#000000',
    tier: 'free',
    features: ['Runtime', 'TypeScript', 'Deno Deploy', 'Secure'],
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    category: 'development',
    description: 'React framework',
    icon: 'https://nextjs.org/favicon.ico',
    website: 'https://nextjs.org',
    color: '#000000',
    tier: 'free',
    features: ['SSR', 'API Routes', 'App Router', 'Optimizations'],
  },
  {
    id: 'nuxt',
    name: 'Nuxt',
    category: 'development',
    description: 'Vue framework',
    icon: 'https://nuxt.com/favicon.ico',
    website: 'https://nuxt.com',
    color: '#00DC82',
    tier: 'free',
    features: ['SSR', 'SEO', 'Auto-imports', 'Modules'],
  },
  {
    id: 'remix',
    name: 'Remix',
    category: 'development',
    description: 'Full stack web framework',
    icon: 'https://remix.run/favicon.ico',
    website: 'https://remix.run',
    color: '#000000',
    tier: 'free',
    features: ['SSR', 'Loaders', 'Actions', 'Nested'],
  },
  {
    id: 'sveltekit',
    name: 'SvelteKit',
    category: 'development',
    description: 'Svelte framework',
    icon: 'https://svelte.dev/favicon.ico',
    website: 'https://svelte.dev',
    color: '#FF3E00',
    tier: 'free',
    features: ['SSR', 'Adapter', 'Code Splitting', 'Hydration'],
  },
  {
    id: 'prisma',
    name: 'Prisma',
    category: 'development',
    description: 'Database ORM',
    icon: 'https://www.prisma.io/favicon.ico',
    website: 'https://prisma.io',
    color: '#2D3748',
    tier: 'free',
    features: ['ORM', 'Migrations', 'Client', 'Studio'],
  },
  {
    id: 'drizzle',
    name: 'Drizzle ORM',
    category: 'development',
    description: 'Type-safe ORM',
    icon: 'https://drizzle-orm.com/favicon.ico',
    website: 'https://drizzle-orm.com',
    color: '#000000',
    tier: 'free',
    features: ['Type-safe', 'Lightweight', 'Migrations', 'SQL-like'],
  },
  {
    id: 'sequel',
    name: 'Sequelize',
    category: 'development',
    description: 'Promise-based ORM',
    icon: 'https://sequelize.org/favicon.ico',
    website: 'https://sequelize.org',
    color: '#3B7BD4',
    tier: 'free',
    features: ['ORM', 'Migrations', 'Associations', 'Validators'],
  },
  {
    id: 'typeorm',
    name: 'TypeORM',
    category: 'development',
    description: 'ORM for TypeScript',
    icon: 'https://typeorm.io/favicon.ico',
    website: 'https://typeorm.io',
    color: '#000000',
    tier: 'free',
    features: ['ORM', 'Active Record', 'Data Mapper', 'Migrations'],
  },
  {
    id: 'graphql',
    name: 'GraphQL',
    category: 'development',
    description: 'Query language for APIs',
    icon: 'https://graphql.org/favicon.ico',
    website: 'https://graphql.org',
    color: '#E10098',
    tier: 'free',
    features: ['Queries', 'Mutations', 'Subscriptions', 'Schema'],
  },
  {
    id: 'apollo',
    name: 'Apollo',
    category: 'development',
    description: 'GraphQL platform',
    icon: 'https://www.apollographql.com/favicon.ico',
    website: 'https://www.apollographql.com',
    color: '#311C87',
    tier: 'free',
    features: ['Client', 'Server', 'Gateway', 'Federation'],
  },
  {
    id: 'urql',
    name: 'urql',
    category: 'development',
    description: 'Lightweight GraphQL client',
    icon: 'https://formidable.com/urql/favicon.ico',
    website: 'https://formidable.com/open-source/urql',
    color: '#000000',
    tier: 'free',
    features: ['Lightweight', 'Exchanges', 'Normalized Cache', 'Universal'],
  },
  {
    id: 'rest',
    name: 'REST API',
    category: 'development',
    description: 'Web service architecture',
    icon: 'https://www.redocly.com/favicon.ico',
    website: 'https://restfulapi.net',
    color: '#6B46C1',
    tier: 'free',
    features: ['HTTP Methods', 'JSON', 'Stateless', 'Resource-based'],
  },
  {
    id: 'trpc',
    name: 'tRPC',
    category: 'development',
    description: 'Type-safe APIs',
    icon: 'https://trpc.io/favicon.ico',
    website: 'https://trpc.io',
    color: '#000000',
    tier: 'free',
    features: ['Type-safe', 'No Schema', 'Performance', 'Subscriptions'],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'finance',
    description: 'Payment infrastructure',
    icon: 'https://stripe.com/favicon.ico',
    website: 'https://stripe.com',
    color: '#635BFF',
    tier: 'free',
    features: ['Payments', 'Connect', 'Radar', 'Billing'],
  },
  {
    id: 'paddle',
    name: 'Paddle',
    category: 'finance',
    description: 'Payment infrastructure',
    icon: 'https://paddle.com/favicon.ico',
    website: 'https://paddle.com',
    color: '#000000',
    tier: 'starter',
    features: ['Payments', 'Subscriptions', 'Tax', 'Global'],
  },
  {
    id: 'lemonsqueezy',
    name: 'Lemon Squeezy',
    category: 'finance',
    description: 'Merchant of record',
    icon: 'https://www.lemonsqueezy.com/favicon.ico',
    website: 'https://www.lemonsqueezy.com',
    color: '#FFBE0B',
    tier: 'free',
    features: ['Payments', 'Subscriptions', 'Tax', 'Global'],
  },
  {
    id: 'gumroad',
    name: 'Gumroad',
    category: 'finance',
    description: 'Creator monetization',
    icon: 'https://gumroad.com/favicon.ico',
    website: 'https://gumroad.com',
    color: '#000000',
    tier: 'free',
    features: ['Products', 'Memberships', 'Licenses', 'Commission'],
  },
  {
    id: 'koji',
    name: 'Koji',
    category: 'finance',
    description: 'Creator monetization',
    icon: 'https://koji.com/favicon.ico',
    website: 'https://koji.com',
    color: '#000000',
    tier: 'free',
    features: ['Store', 'Tips', 'Links', 'Creator Tools'],
  },
  {
    id: 'polar',
    name: 'Polar',
    category: 'finance',
    description: 'Subscriptions for creators',
    icon: 'https://polar.io/favicon.ico',
    website: 'https://polar.io',
    color: '#000000',
    tier: 'free',
    features: ['Subscriptions', 'Benefits', 'Payments', 'Analytics'],
  },
  {
    id: 'twillio',
    name: 'Twilio',
    category: 'communication',
    description: 'Communication APIs',
    icon: 'https://twilio.com/favicon.ico',
    website: 'https://twilio.com',
    color: '#F22F46',
    tier: 'free',
    features: ['SMS', 'Voice', 'Video', 'Verify'],
  },
  {
    id: 'sendgrid',
    name: 'SendGrid',
    category: 'communication',
    description: 'Email delivery',
    icon: 'https://sendgrid.com/favicon.ico',
    website: 'https://sendgrid.com',
    color: '#1A82E2',
    tier: 'free',
    features: ['Email API', 'Templates', 'Analytics', 'Inbound'],
  },
  {
    id: 'mailgun',
    name: 'Mailgun',
    category: 'communication',
    description: 'Email API service',
    icon: 'https://mailgun.com/favicon.ico',
    website: 'https://mailgun.com',
    color: '#A51524',
    tier: 'free',
    features: ['Email API', 'Tracking', 'Templates', 'Webhooks'],
  },
  {
    id: 'postmark',
    name: 'Postmark',
    category: 'communication',
    description: 'Email delivery service',
    icon: 'https://postmarkapp.com/favicon.ico',
    website: 'https://postmarkapp.com',
    color: '#000000',
    tier: 'free',
    features: ['Transactional Email', 'Delivery', 'Tracking', 'Templates'],
  },
  {
    id: 'resend',
    name: 'Resend',
    category: 'communication',
    description: 'Email for developers',
    icon: 'https://resend.com/favicon.ico',
    website: 'https://resend.com',
    color: '#000000',
    tier: 'free',
    features: ['Email API', 'React Email', 'Templates', 'Webhook'],
  },
  {
    id: 'plunk',
    name: 'Plunk',
    category: 'communication',
    description: 'Email platform',
    icon: 'https://www.plunk.email/favicon.ico',
    website: 'https://www.plunk.email',
    color: '#000000',
    tier: 'free',
    features: ['Email', 'Automation', 'Analytics', 'Templates'],
  },
  {
    id: 'convertkit',
    name: 'ConvertKit',
    category: 'marketing',
    description: 'Email marketing for creators',
    icon: 'https://convertkit.com/favicon.ico',
    website: 'https://convertkit.com',
    color: '#FB9F3D',
    tier: 'free',
    features: ['Email', 'Forms', 'Automations', 'Landing Pages'],
  },
  {
    id: 'buttondown',
    name: 'Buttondown',
    category: 'marketing',
    description: 'Minimalist newsletter',
    icon: 'https://buttondown.email/favicon.ico',
    website: 'https://buttondown.email',
    color: '#000000',
    tier: 'free',
    features: ['Newsletter', 'Analytics', 'Templates', 'API'],
  },
  {
    id: 'ghost',
    name: 'Ghost',
    category: 'marketing',
    description: 'Publishing platform',
    icon: 'https://ghost.org/favicon.ico',
    website: 'https://ghost.org',
    color: '#000000',
    tier: 'free',
    features: ['CMS', 'Newsletter', 'Membership', 'Analytics'],
  },
  {
    id: 'substack',
    name: 'Substack',
    category: 'marketing',
    description: 'Newsletter platform',
    icon: 'https://substack.com/favicon.ico',
    website: 'https://substack.com',
    color: '#000000',
    tier: 'free',
    features: ['Newsletter', 'Publishing', 'Payments', 'Podcast'],
  },
  {
    id: 'revue',
    name: 'Revue',
    category: 'marketing',
    description: 'Newsletter by Twitter',
    icon: 'https://www.revue.io/favicon.ico',
    website: 'https://www.revue.io',
    color: '#000000',
    tier: 'free',
    features: ['Newsletters', 'Analytics', 'Templates', 'Scheduling'],
  },
  {
    id: 'beehiiv',
    name: 'Beehiiv',
    category: 'marketing',
    description: 'Newsletter platform',
    icon: 'https://www.beehiiv.com/favicon.ico',
    website: 'https://www.beehiiv.com',
    color: '#000000',
    tier: 'free',
    features: ['Newsletter', 'Growth', 'Analytics', 'Ads'],
  },
  {
    id: 'sendinblue',
    name: 'Sendinblue',
    category: 'marketing',
    description: 'Email marketing',
    icon: 'https://www.sendinblue.com/favicon.ico',
    website: 'https://www.sendinblue.com',
    color: '#0092FF',
    tier: 'free',
    features: ['Email', 'SMS', 'Chat', 'CRM'],
  },
  {
    id: 'getresponse',
    name: 'GetResponse',
    category: 'marketing',
    description: 'Email marketing',
    icon: 'https://www.getresponse.com/favicon.ico',
    website: 'https://www.getresponse.com',
    color: '#00B4D2',
    tier: 'free',
    features: ['Email', 'Landing Pages', 'Automation', 'Ecommerce'],
  },
  {
    id: 'activecampaign',
    name: 'ActiveCampaign',
    category: 'marketing',
    description: 'Marketing automation',
    icon: 'https://www.activecampaign.com/favicon.ico',
    website: 'https://www.activecampaign.com',
    color: '#356AE6',
    tier: 'free',
    features: ['Automation', 'CRM', 'Email', 'Site Tracking'],
  },
  {
    id: 'webflow',
    name: 'Webflow',
    category: 'design',
    description: 'Visual web development',
    icon: 'https://webflow.com/favicon.ico',
    website: 'https://webflow.com',
    color: '#000000',
    tier: 'free',
    features: ['Visual Editor', 'CMS', 'Ecommerce', 'Interactions'],
  },
  {
    id: 'squarespace',
    name: 'Squarespace',
    category: 'design',
    description: 'Website builder',
    icon: 'https://squarespace.com/favicon.ico',
    website: 'https://squarespace.com',
    color: '#000000',
    tier: 'starter',
    features: ['Templates', 'Commerce', 'Scheduling', 'Analytics'],
  },
  {
    id: 'wix',
    name: 'Wix',
    category: 'design',
    description: 'Website builder',
    icon: 'https://www.wix.com/favicon.ico',
    website: 'https://www.wix.com',
    color: '#0C2E5A',
    tier: 'free',
    features: ['Drag & Drop', 'Wix ADI', 'Ecommerce', 'Blog'],
  },
  {
    id: 'carrd',
    name: 'Carrd',
    category: 'design',
    description: 'Simple one-page sites',
    icon: 'https://carrd.co/favicon.ico',
    website: 'https://carrd.co',
    color: '#000000',
    tier: 'free',
    features: ['One-page', 'Templates', 'Custom Domain', 'Pro'],
  },
  {
    id: 'framer sites',
    name: 'Framer',
    category: 'design',
    description: 'Design and publish sites',
    icon: 'https://www.framer.com/favicon.ico',
    website: 'https://www.framer.com/sites',
    color: '#000000',
    tier: 'free',
    features: ['Design', 'Publishing', 'CMS', 'Animations'],
  },
  {
    id: 'readymag',
    name: 'Readymag',
    category: 'design',
    description: 'Digital publishing',
    icon: 'https://readymag.com/favicon.ico',
    website: 'https://readymag.com',
    color: '#000000',
    tier: 'free',
    features: ['Publishing', 'Typography', 'Animations', 'Ecommerce'],
  },
  {
    id: 'uxpin',
    name: 'UXPin',
    category: 'design',
    description: 'UX design tool',
    icon: 'https://www.uxpin.com/favicon.ico',
    website: 'https://www.uxpin.com',
    color: '#000000',
    tier: 'free',
    features: ['Prototyping', 'Design Systems', 'Collaboration', 'Testing'],
  },
  {
    id: 'figjam',
    name: 'FigJam',
    category: 'design',
    description: 'Online whiteboard',
    icon: 'https://www.figma.com/figjam/favicon.ico',
    website: 'https://www.figma.com/figjam',
    color: '#F24E1E',
    tier: 'free',
    features: ['Whiteboard', 'Sticky Notes', 'Templates', 'Plugins'],
  },
  {
    id: 'miro',
    name: 'Miro',
    category: 'design',
    description: 'Visual collaboration',
    icon: 'https://miro.com/favicon.ico',
    website: 'https://miro.com',
    color: '#FFD02F',
    tier: 'free',
    features: ['Whiteboard', 'Templates', 'Apps', 'Facilitation'],
  },
  {
    id: 'mural',
    name: 'Mural',
    category: 'design',
    description: 'Collaborative canvas',
    icon: 'https://mural.co/favicon.ico',
    website: 'https://mural.co',
    color: '#FF0085',
    tier: 'free',
    features: ['Canvas', 'Templates', 'Facilitator', 'Integrations'],
  },
  {
    id: 'miro',
    name: 'Jam',
    category: 'development',
    description: 'Developer collaboration',
    icon: 'https://jam.dev/favicon.ico',
    website: 'https://jam.dev',
    color: '#000000',
    tier: 'free',
    features: ['Debugging', 'Screen Share', 'Voice', 'Comments'],
  },
  {
    id: 'codestream',
    name: 'CodeStream',
    category: 'development',
    description: 'Code collaboration',
    icon: 'https://codestream.com/favicon.ico',
    website: 'https://codestream.com',
    color: '#000000',
    tier: 'free',
    features: ['Code Review', 'Discussion', 'Snippets', 'Workflows'],
  },
  {
    id: 'gitkraken',
    name: 'GitKraken',
    category: 'development',
    description: 'Git GUI client',
    icon: 'https://www.gitkraken.com/favicon.ico',
    website: 'https://www.gitkraken.com',
    color: '#179287',
    tier: 'free',
    features: ['Git GUI', 'Gists', 'Diff View', 'Issue Tracking'],
  },
  {
    id: 'sourcetree',
    name: 'Sourcetree',
    category: 'development',
    description: 'Git GUI client',
    icon: 'https://www.sourcetreeapp.com/favicon.ico',
    website: 'https://www.sourcetreeapp.com',
    color: '#0078C7',
    tier: 'free',
    features: ['Git GUI', 'Submodules', 'Diff View', 'Merge'],
  },
  {
    id: 'tower',
    name: 'Tower',
    category: 'development',
    description: 'Git client for Mac',
    icon: 'https://www.git-tower.com/favicon.ico',
    website: 'https://www.git-tower.com',
    color: '#1C375B',
    tier: 'free',
    features: ['Git GUI', 'Version Control', 'Submodules', 'Blame'],
  },
  {
    id: 'github desktop',
    name: 'GitHub Desktop',
    category: 'development',
    description: 'GitHub desktop app',
    icon: 'https://github.githubassets.com/favicon.ico',
    website: 'https://desktop.github.com',
    color: '#181717',
    tier: 'free',
    features: ['Git GUI', 'Pull Requests', 'Sync', 'History'],
  },
  {
    id: 'git',
    name: 'Git',
    category: 'development',
    description: 'Version control system',
    icon: 'https://git-scm.com/favicon.ico',
    website: 'https://git-scm.com',
    color: '#F05032',
    tier: 'free',
    features: ['Version Control', 'Branching', 'Merging', 'Hooks'],
  },
  {
    id: 'bitbucket',
    name: 'Azure DevOps',
    category: 'development',
    description: 'Microsoft DevOps',
    icon: 'https://azure.microsoft.com/favicon.ico',
    website: 'https://azure.microsoft.com/services/devops',
    color: '#0078D4',
    tier: 'free',
    features: ['Pipelines', 'Repos', 'Boards', 'Test Plans'],
  },
  {
    id: 'jira',
    name: 'Jira',
    category: 'productivity',
    description: 'Project tracking',
    icon: 'https://jira.com/favicon.ico',
    website: 'https://jira.com',
    color: '#0052CC',
    tier: 'free',
    features: ['Issues', 'Scrum', 'Kanban', 'Roadmaps'],
  },
  {
    id: 'confluence',
    name: 'Confluence',
    category: 'productivity',
    description: 'Team wiki',
    icon: 'https://confluence.com/favicon.ico',
    website: 'https://confluence.com',
    color: '#0052CC',
    tier: 'free',
    features: ['Pages', 'Templates', 'Spaces', 'Search'],
  },
  {
    id: 'youtrack',
    name: 'YouTrack',
    category: 'productivity',
    description: 'Issue tracker',
    icon: 'https://youtrack.org/favicon.ico',
    website: 'https://youtrack.org',
    color: '#000000',
    tier: 'free',
    features: ['Issues', 'Agile', 'Knowledge Base', 'Inbox'],
  },
  {
    id: 'shortcut',
    name: 'Shortcut',
    category: 'productivity',
    description: 'Project management',
    icon: 'https://shortcut.com/favicon.ico',
    website: 'https://shortcut.com',
    color: '#000000',
    tier: 'free',
    features: ['Stories', 'Epics', 'Workflows', 'Search'],
  },
  {
    id: 'vivy',
    name: 'Clubhouse',
    category: 'productivity',
    description: 'Project management',
    icon: 'https://clubhouse.io/favicon.ico',
    website: 'https://clubhouse.io',
    color: '#000000',
    tier: 'free',
    features: ['Stories', 'Workflows', 'Labels', 'Integrations'],
  },
];

export const integrationsByCategory = integrationCategories.reduce((acc, cat) => {
  acc[cat.id] = integrations.filter((i) => i.category === cat.id);
  return acc;
}, {} as Record<IntegrationCategory, Integration[]>);

export const getIntegrationsByTier = (tier: Integration['tier']) => {
  return integrations.filter((i) => i.tier === tier);
};

export const searchIntegrations = (query: string) => {
  const q = query.toLowerCase();
  return integrations.filter(
    (i) =>
      i.name.toLowerCase().includes(q) ||
      i.description.toLowerCase().includes(q) ||
      i.features.some((f) => f.toLowerCase().includes(q))
  );
};

export const PLANS = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    period: 'forever',
    features: [
      'Unlimited conversations',
      '20 built-in skills',
      'Memory storage (100 items)',
      'Basic model access',
      'Web3 wallet auth',
    ],
    limits: {
      messagesPerDay: 50,
      memories: 100,
      skills: 20,
    },
  },
  {
    id: 'starter',
    name: 'Starter',
    price: 10,
    period: 'quarter',
    tier: 'starter',
    trialDays: 7,
    features: [
      'Everything in Free',
      '1000+ app integrations',
      'Memory storage (1,000)',
      'Priority models',
      'Basic support',
    ],
    limits: {
      messagesPerDay: 200,
      memories: 1000,
      skills: 50,
    },
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 30,
    period: 'quarter',
    tier: 'pro',
    trialDays: 7,
    popular: true,
    features: [
      'Everything in Starter',
      'Unlimited memory',
      'All models access',
      'Custom skills',
      'Scheduled tasks',
      'Priority support',
    ],
    limits: {
      messagesPerDay: 1000,
      memories: -1,
      skills: 100,
    },
  },
  {
    id: 'ultra',
    name: 'Ultra',
    price: 50,
    period: 'quarter',
    tier: 'ultra',
    trialDays: 7,
    features: [
      'Everything in Pro',
      'Unlimited everything',
      'Early access features',
      'Dedicated support',
      'API access',
    ],
    limits: {
      messagesPerDay: -1,
      memories: -1,
      skills: -1,
    },
  },
] as const;

export type PlanId = typeof PLANS[number]['id'];